"""empty message

Revision ID: 3b6f274db24e
Revises: 7229985b9fec
Create Date: 2019-11-16 19:15:06.212740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b6f274db24e'
down_revision = '7229985b9fec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('text', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_post', 'text')
    # ### end Alembic commands ###
