"""empty message

Revision ID: a95fd1b9ce77
Revises: 3b6f274db24e
Create Date: 2019-11-16 19:17:47.172988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a95fd1b9ce77'
down_revision = '3b6f274db24e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_post', 'text')
    # ### end Alembic commands ###
